name: Deploy to Render

on:
  push:
    branches:
      - main  # Runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        run: |
          curl "https://api.render.com/deploy/srv-d2tem8mr433s73dbklp0?key=NY7f2FU8YOk"
        env:
          RENDER_DEPLOY_HOOK: "https://api.render.com/deploy/srv-d2tem8mr433s73dbklp0?key=NY7f2FU8YOk"
